import { setExtensionPrompt, extension_prompt_types, eventSource, event_types } from '../../../../script.js';
import { getContext } from '../../../extensions.js';

const META_KEY='lovemed_state_v1', UI_KEY='lovemed_ui_v1', GLOBAL_KEY='lovemed_library_v1', REL_MAX=200;
const REL_FIELDS=[
['trust','Доверие'],['affection','Привязанность'],['love','Любовь'],['sympathy','Симпатия'],['friendship','Дружба'],['respect','Уважение'],
['desire','Желание'],['passion','Страсть'],['arousal','Возбуждение'],['obsession','Одержимость'],['tenderness','Нежность'],['admiration','Восхищение'],
['jealousy','Ревность'],['resentment','Обида'],['irritation','Раздражение'],['anger','Злость'],['fear','Страх'],['sadness','Грусть'],
['disappointment','Разочарование'],['joy','Радость'],['fondness','Умиление'],['stress','Стресс'],['tension','Напряжение'],['antipathy','Антипатия'],['hate','Ненависть']];
const REL_LABEL=Object.fromEntries(REL_FIELDS), DEFAULT_VISIBLE=['love','trust','affection','desire','tension','tenderness'];
const KINKS=[
['dominance','Доминирование','psych'],['submission','Подчинение','psych'],['praise','Похвала','psych'],['teasing','Дразнение','psych'],['powerplay','Игра власти','psych'],['control','Контроль','psych'],['service','Забота / сервисная динамика','psych'],
['bondage','Фиксация / бондаж','physical'],['blindfold','Повязка на глаза','physical'],['spanking','Шлепки','physical'],['biting','Укусы','physical'],['hair','Волосы','physical'],['marking','Метки / следы','physical'],['sensory','Сенсорная стимуляция','physical'],['toys','Игрушки','physical'],
['roleplay','Ролевые сценарии','situational'],['voyeurism','Наблюдение','situational'],['exhibitionism','Эксгибиционистская динамика','situational'],['risk','Риск / запретность','situational'],['costume','Костюмы / образы','situational'],['phone','Телефонная / голосовая динамика','situational'],['sexting','Интимная переписка','situational'],
['slowburn','Постепенное сближение','romantic'],['aftercare','Забота после близости','romantic'],['romantic','Романтическая близость','romantic'],['gentle','Нежная динамика','romantic'],['rough','Грубая динамика','physical']];
const KINK_WORDS={
dominance:['dominant','domination','dominance','доминир','ведущая роль'],submission:['submissive','submission','подчинен','подчинён','послушн'],
praise:['praise','good girl','good boy','похвал','умница'],teasing:['teasing','tease','дразн','поддразн','провоцир'],
powerplay:['power play','power exchange','игра власти'],control:['control kink','control fetish','контроль'],service:['service kink','care kink','забота о партнёре'],
bondage:['bondage','restraint','tie up','ropes','бондаж','связ','фиксац'],blindfold:['blindfold','eyes covered','повяз','завязанные глаза'],
spanking:['spank','spanking','шлеп','шлёп'],biting:['bite','biting','nibble','укусы','куса','прикус'],hair:['hair pull','pulling hair','grab hair','волос','за волосы'],
marking:['marking','love bites','hickeys','следы','метки','засос'],sensory:['sensory play','temperature play','ice play','wax play','сенсорн','температур','лёд','воск'],toys:['sex toy','toys','игрушк'],
roleplay:['roleplay','role play','ролевая игра','ролевые игры'],voyeurism:['voyeur','watching','вуайер','подглядыв','наблюдать'],
exhibitionism:['exhibitionism','exhibitionist','эксгибиционизм'],risk:['risk','forbidden','danger of being caught','запретн','риск быть пойман','на грани'],
costume:['costume','uniform kink','dress up','костюм','форма','образ'],phone:['phone sex','voice sex','секс по телефону','голосовой секс'],
sexting:['sexting','sexual texting','секстинг','интимная переписка'],slowburn:['slow burn','slowburn','gradual intimacy','медленн','постепенное сближение'],
aftercare:['aftercare','care after','после близости','забота после'],romantic:['romantic intimacy','tender intimacy','нежная близость','романтическая близость'],
gentle:['gentle sex','soft sex','tender sex','нежный','мягкая близость'],rough:['rough sex','rough intimacy','грубая близость','грубый секс']};
const CAT_LABEL={psych:'Психологические',physical:'Физические / сенсорные',situational:'Ситуационные',romantic:'Романтические'};
const defaults=()=>({enabled:true,autoTrack:true,autoReaction:true,relation:Object.fromEntries(REL_FIELDS.map(([k])=>[k,0])),activeFeelings:[],lastShift:'',diagnosis:[],anamnesis:[],anamnesisAt:0,reactionIntensity:55,reactionChance:35,reactionCooldown:4,reactionCooldownRemaining:0,lastReaction:'',contacts:[],history:[],charName:'',updatedAt:Date.now(),diagnostics:{lastParseAt:0,lastParseStatus:'Ожидает проверки',lastParseError:''}});
const ctx=()=>{try{return getContext?.()||globalThis.SillyTavern?.getContext?.()||{};}catch{return {};}};
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const clamp=(n,min=0,max=REL_MAX)=>Math.max(min,Math.min(max,Number(n)||0));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function merge(raw){const d=defaults(),s=Object.assign(d,raw||{});s.relation=Object.assign({},d.relation,raw?.relation||{});for(const k of ['activeFeelings','diagnosis','anamnesis','contacts','history'])if(!Array.isArray(s[k]))s[k]=[];s.diagnostics=Object.assign({},d.diagnostics,raw?.diagnostics||{});return s;}
function chatKey(){const c=ctx(),who=c.groupId?`group-${c.groupId}`:`char-${c.characterId??'none'}`,chat=c.chatId||c.chatFile||c.chatMetadata?.chat_id||c.chatMetadata?.file_name||'current';return `${who}:${String(chat)}`.replace(/[^a-zA-Z0-9_.:-]/g,'_').slice(0,220);}
function getState(){const c=ctx();let m=null,b=null;try{m=c.chatMetadata?.[META_KEY]||null;}catch{}try{b=JSON.parse(localStorage.getItem(`lovemed_backup:${chatKey()}`)||'null');}catch{}return merge(m&&b?((b.updatedAt||0)>(m.updatedAt||0)?b:m):(m||b));}
async function saveState(s=getState()){s.updatedAt=Date.now();const c=ctx();try{if(c.chatMetadata)c.chatMetadata[META_KEY]=s;await c.saveMetadata?.();}catch{}try{localStorage.setItem(`lovemed_backup:${chatKey()}`,JSON.stringify(s));}catch{}refreshPrompt();}
function getLibrary(){try{const x=JSON.parse(localStorage.getItem(GLOBAL_KEY)||'[]');return Array.isArray(x)?x:[];}catch{return[];}}
function saveLibrary(x){try{localStorage.setItem(GLOBAL_KEY,JSON.stringify(x));}catch{}}
function allKinks(){return KINKS.map(([id,name,cat])=>({id,name,cat,words:KINK_WORDS[id]||[]})).concat(getLibrary());}
function charName(){const c=ctx(),ch=c?.characters?.[c?.characterId];return ch?.name||ch?.data?.name||'{{char}}';}
function cardText(){const c=ctx();if(!c||c.groupId)return'';const ch=c.characters?.[c.characterId];if(!ch)return'';const out=[],seen=new WeakSet(),skip=/^(avatar|image|thumbnail|chat|date_last_chat|create_date)$/i;function walk(v,k='',d=0){if(d>5||v==null||skip.test(k))return;if(typeof v==='string'){if(v.trim()&&v.length<50000)out.push(v.trim());return;}if(typeof v!=='object'||seen.has(v))return;seen.add(v);if(Array.isArray(v)){v.slice(0,150).forEach(x=>walk(x,k,d+1));return;}Object.entries(v).forEach(([kk,vv])=>walk(vv,kk,d+1));}walk(ch,'character');return out.join('\n').toLowerCase();}
function scan(){const t=cardText();if(!t)return[];return[...new Set(allKinks().filter(k=>(k.words||[]).some(w=>t.includes(String(w).toLowerCase()))).map(k=>k.id))];}
function kink(id){return allKinks().find(k=>k.id===id)||{id,name:id,cat:'psych',words:[]};}
function anamnesis(){const s=getState(),f=scan();s.anamnesis=f;s.diagnosis=f;s.anamnesisAt=Date.now();s.history.unshift({ts:Date.now(),text:`Анамнез обновлён: обнаружено ${f.length} предпочтений.`});s.history=s.history.slice(0,40);saveState(s);render();toast(`Анамнез: найдено ${f.length}`);}
function visible(s){const a=(s.activeFeelings||[]).filter(k=>REL_LABEL[k]),r=REL_FIELDS.map(([k])=>[k,clamp(s.relation[k])]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);return[...new Set([...a,...r,...DEFAULT_VISIBLE])].slice(0,6);}
function parsePacket(text){const o='[[LOVEMED_STATE]]',c='[[/LOVEMED_STATE]]',p=text.lastIndexOf(o);if(p<0)return null;const q=text.indexOf(c,p+o.length);if(q<0)return null;try{return{packet:JSON.parse(text.slice(p+o.length,q).trim()),start:p,end:q+c.length};}catch{return null;}}
function applyPacket(s,p){if(p.relation)for(const[k,v]of Object.entries(p.relation))if(k in s.relation)s.relation[k]=clamp(s.relation[k]+Number(v));if(Array.isArray(p.active_feelings))s.activeFeelings=p.active_feelings.filter(k=>REL_LABEL[k]).slice(0,6);if(p.shift)s.lastShift=String(p.shift).slice(0,300);if(Array.isArray(p.contacts))for(const n of p.contacts){if(!n?.name)continue;let x=s.contacts.find(v=>v.name.toLowerCase()===String(n.name).toLowerCase());if(!x){x={id:uid(),name:String(n.name),relation:'Не определено',notes:''};s.contacts.push(x);}x.relation=String(n.relation||x.relation).slice(0,100);x.notes=String(n.notes||x.notes).slice(0,300);x.updatedAt=Date.now();}s.history.unshift({ts:Date.now(),text:s.lastShift||'Медицинские показатели обновлены.'});s.history=s.history.slice(0,40);}
function parseLatest(){const c=ctx();if(!c?.chat)return false;const x=[...c.chat].map((m,i)=>({m,i})).reverse().find(v=>!v.m.is_user&&typeof v.m.mes==='string');if(!x)return false;const f=parsePacket(x.m.mes);if(!f)return false;const s=getState();applyPacket(s,f.packet);s.diagnostics={lastParseAt:Date.now(),lastParseStatus:'Служебный пакет принят ✓',lastParseError:''};x.m.mes=(x.m.mes.slice(0,f.start)+x.m.mes.slice(f.end)).trimEnd();try{c.chat[x.i]=x.m;c.saveChat?.();}catch{}saveState(s);return true;}
function reactionPrompt(s){if(!s.autoReaction||!(s.anamnesis||[]).length)return'';if(s.reactionCooldownRemaining>0){s.reactionCooldownRemaining--;return'';}if(Math.random()*100>s.reactionChance)return'';const pick=s.anamnesis[Math.floor(Math.random()*s.anamnesis.length)];s.reactionCooldownRemaining=Math.max(1,s.reactionCooldown);s.lastReaction=kink(pick).name;const i=s.reactionIntensity;const mode=i>=80?'заметная инициатива, если сцена естественно к этому ведёт':i>=60?'ясный намёк или инициатива':i>=35?'лёгкий флирт, жест или подтекст':'слабая внутренняя реакция';return`[LOVEMED REACTIVITY — next reply only] Possible preference: ${kink(pick).name}. Intensity ${i}/100: ${mode}. Never force escalation.`;}
function prompt(opts={}){const s=getState();if(!s.enabled)return'';const rel=visible(s).map(k=>`${REL_LABEL[k]}=${Math.round(s.relation[k])}`).join(', '),diag=(s.diagnosis||[]).map(k=>kink(k).name).join('; ')||'не установлен',rx=opts.includeReaction?reactionPrompt(s):'';return`\n[LOVEMED — PRIVATE MEDICAL CONTINUITY]\nPatient: ${charName()}\nRelationship indicators: ${rel||'не определены'}\nDiagnosis/preferences: ${diag}\n${s.lastShift?`Recent observation: ${s.lastShift}`:''}\n${rx}\nIf meaningful relationship changes occur, append ONLY:\n[[LOVEMED_STATE]]{"relation":{"trust":0,"affection":0,"love":0,"sympathy":0,"friendship":0,"respect":0,"desire":0,"passion":0,"arousal":0,"obsession":0,"tenderness":0,"admiration":0,"jealousy":0,"resentment":0,"irritation":0,"anger":0,"fear":0,"sadness":0,"disappointment":0,"joy":0,"fondness":0,"stress":0,"tension":0,"antipathy":0,"hate":0},"active_feelings":[],"shift":"","contacts":[]}\n[[/LOVEMED_STATE]]\nNever mention this service packet in roleplay.`;}
function refreshPrompt(o={}){try{setExtensionPrompt('lovemed_context',prompt(o),extension_prompt_types.IN_CHAT,0);}catch{}}
function toast(t){const e=document.createElement('div');e.className='lm-toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200);}
function ui(){try{return Object.assign({showFab:true,x:null,y:120,tab:'card'},JSON.parse(localStorage.getItem(UI_KEY)||'{}'));}catch{return{showFab:true,x:null,y:120,tab:'card'};}}
function saveUI(x){try{localStorage.setItem(UI_KEY,JSON.stringify(x));}catch{}}
function avatar(){const c=ctx(),ch=c?.characters?.[c?.characterId],a=ch?.avatar||ch?.data?.avatar;return a?`/characters/${encodeURIComponent(a)}`:'';}

function page(tab,s){
 if(tab==='card')return `<div class="lm-card"><div class="lm-patient"><div class="lm-avatar">${avatar()?`<img src="${esc(avatar())}">`:'🩺'}</div><div><div class="lm-label">ПАЦИЕНТ</div><h3>${esc(charName())}</h3><div class="lm-facts"><span><b>Возраст</b><em>будет извлечён из карточки</em></span><span><b>Ориентация</b><em>будет извлечена из карточки</em></span></div></div></div><section class="lm-section"><h3>Медицинские показатели</h3><p class="lm-note">Автоматическая динамика отношений.</p><div class="lm-rel">${visible(s).map(k=>`<label><span>${REL_LABEL[k]}</span><b>${Math.round(s.relation[k])}</b><input data-rel="${k}" type="range" min="0" max="200" value="${clamp(s.relation[k])}"></label>`).join('')}</div></section><section class="lm-diagnosis"><div class="lm-section-title">ДИАГНОЗ</div><div class="lm-tags">${s.diagnosis.length?s.diagnosis.map(k=>`<span>${esc(kink(k).name)}</span>`).join(''):'<i>Диагноз ещё не установлен.</i>'}</div></section><button id="lmAnamnesis" class="lm-primary">🩺 Провести анамнез карточки пациента</button></div>`;
 if(tab==='react'){const cats={psych:[],physical:[],situational:[],romantic:[]};allKinks().forEach(k=>(cats[k.cat]||cats.psych).push(k));return `<div class="lm-card"><section class="lm-section"><h3>Реактивность пациента</h3><div class="lm-sliders"><label>Интенсивность реакции <b>${s.reactionIntensity}</b><input id="lmIntensity" type="range" min="0" max="100" value="${s.reactionIntensity}"></label><label>Вероятность спонтанной реакции <b>${s.reactionChance}%</b><input id="lmChance" type="range" min="0" max="100" value="${s.reactionChance}"></label><label>Период наблюдения <b>${s.reactionCooldown}</b><input id="lmCooldown" type="range" min="1" max="12" value="${s.reactionCooldown}"></label></div></section><section class="lm-section"><h3>Библиотека предпочтений</h3>${Object.entries(cats).map(([cat,list])=>`<details open class="lm-fold"><summary>${CAT_LABEL[cat]}</summary><div class="lm-kinks">${list.map(k=>`<span class="${s.anamnesis.includes(k.id)?'found':''}">${esc(k.name)}</span>`).join('')}</div></details>`).join('')}</section><section class="lm-section"><h3>Моя библиотека</h3><div class="lm-custom-form"><input id="lmKinkName" placeholder="Название предпочтения"><select id="lmKinkCat">${Object.entries(CAT_LABEL).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><textarea id="lmKinkDesc" placeholder="Описание"></textarea><button id="lmAddKink">+ Добавить</button></div><div class="lm-custom-list">${getLibrary().map(k=>`<div><b>${esc(k.name)}</b><small>${esc(k.description||'')}</small><button data-del-kink="${esc(k.id)}">×</button></div>`).join('')||'<i>Пока пусто.</i>'}</div></section></div>`;}
 if(tab==='diag')return `<div class="lm-card"><section class="lm-section"><h3>Анамнез</h3><p class="lm-note">${s.anamnesisAt?`Последнее обследование: ${new Date(s.anamnesisAt).toLocaleString()}`:'Обследование ещё не проводилось.'}</p><button id="lmAnamnesis2" class="lm-primary">Провести повторное обследование</button>${s.anamnesis.map(k=>`<article class="lm-found"><b>${esc(kink(k).name)}</b><p>Обнаружено в карточке пациента.</p></article>`).join('')||'<p class="lm-note">Совпадений не найдено.</p>'}</section></div>`;
 if(tab==='contacts')return `<div class="lm-card"><section class="lm-section"><h3>Сопутствующие лица</h3><p class="lm-note">Персонажи, влияющие на состояние пациента и отношения.</p>${s.contacts.map(n=>`<article class="lm-contact"><div><b>${esc(n.name)}</b><small>${esc(n.relation||'')}</small><p>${esc(n.notes||'')}</p></div><button data-del-contact="${esc(n.id)}">Удалить</button></article>`).join('')||'<i>Пока нет наблюдаемых контактов.</i>'}</section></div>`;
 if(tab==='history')return `<div class="lm-card"><section class="lm-section"><h3>История наблюдений</h3>${s.history.slice(0,20).map(x=>`<article class="lm-history"><time>${new Date(x.ts).toLocaleString()}</time><span>${esc(x.text)}</span></article>`).join('')||'<i>История пока пуста.</i>'}</section></div>`;
 return `<div class="lm-card"><section class="lm-section"><h3>Служебная диагностика</h3><label class="lm-check"><input id="lmEnabled" type="checkbox" ${s.enabled?'checked':''}> Включить LoveMed</label><label class="lm-check"><input id="lmAutoTrack" type="checkbox" ${s.autoTrack?'checked':''}> Автоматически обновлять показатели</label><label class="lm-check"><input id="lmAutoReaction" type="checkbox" ${s.autoReaction?'checked':''}> Разрешить спонтанные реакции</label><p class="lm-note">${esc(s.diagnostics.lastParseStatus)}</p><button id="lmParse" class="lm-secondary">Проверить последний ответ модели</button><label class="lm-check"><input id="lmFab" type="checkbox" ${ui().showFab?'checked':''}> Показывать плавающую кнопку</label></section></div>`;
}
function render(){const b=document.querySelector('#lmBody');if(!b)return;const s=getState(),u=ui();b.innerHTML=page(u.tab,s);bind();}
function bind(){
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{const u=ui();u.tab=b.dataset.tab;saveUI(u);render();});
 document.querySelectorAll('[data-rel]').forEach(x=>x.oninput=async e=>{const s=getState();s.relation[e.target.dataset.rel]=Number(e.target.value);await saveState(s);render();});
 document.querySelector('#lmAnamnesis')?.addEventListener('click',anamnesis);document.querySelector('#lmAnamnesis2')?.addEventListener('click',anamnesis);
 [['#lmIntensity','reactionIntensity'],['#lmChance','reactionChance'],['#lmCooldown','reactionCooldown']].forEach(([q,k])=>document.querySelector(q)?.addEventListener('input',async e=>{const s=getState();s[k]=Number(e.target.value);await saveState(s);}));
 document.querySelector('#lmAddKink')?.addEventListener('click',()=>{const n=document.querySelector('#lmKinkName').value.trim(),d=document.querySelector('#lmKinkDesc').value.trim(),cat=document.querySelector('#lmKinkCat').value;if(!n)return;const l=getLibrary();l.push({id:`custom-${uid()}`,name:n,description:d,cat,words:[n.toLowerCase()]});saveLibrary(l);render();toast('Добавлено в общую библиотеку');});
 document.querySelectorAll('[data-del-kink]').forEach(b=>b.onclick=()=>{saveLibrary(getLibrary().filter(k=>k.id!==b.dataset.delKink));render();});
 document.querySelectorAll('[data-del-contact]').forEach(b=>b.onclick=async()=>{const s=getState();s.contacts=s.contacts.filter(x=>x.id!==b.dataset.delContact);await saveState(s);render();});
 [['#lmEnabled','enabled'],['#lmAutoTrack','autoTrack'],['#lmAutoReaction','autoReaction']].forEach(([q,k])=>document.querySelector(q)?.addEventListener('change',async e=>{const s=getState();s[k]=e.target.checked;await saveState(s);}));
 document.querySelector('#lmParse')?.addEventListener('click',()=>toast(parseLatest()?'Пакет принят ✓':'Пакет не найден'));
 document.querySelector('#lmFab')?.addEventListener('change',e=>{const u=ui();u.showFab=e.target.checked;saveUI(u);syncFab();});
}
function ensurePanel(){if(document.querySelector('#lmOverlay'))return;document.body.insertAdjacentHTML('beforeend',`<div id="lmOverlay" class="lm-overlay hidden"><section class="lm-panel"><header class="lm-head"><div><div class="lm-kicker">LOVEMED · MEDICAL RECORD v0.1.0</div><h2>Медицинская карта</h2><p>Наблюдение за динамикой отношений</p></div><button id="lmClose" class="lm-close">×</button></header><nav class="lm-tabs">${[['card','🩺 Карта пациента'],['react','🧪 Реактивность'],['diag','🔬 Анамнез'],['contacts','👤 Контакты'],['history','📋 История'],['system','⚙ Служебное']].map(x=>`<button data-tab="${x[0]}">${x[1]}</button>`).join('')}</nav><main id="lmBody"></main></section></div>`);document.querySelector('#lmClose').onclick=()=>document.querySelector('#lmOverlay').classList.add('hidden');}
function open(){ensurePanel();document.querySelector('#lmOverlay').classList.remove('hidden');render();}
function placeFab(){const b=document.querySelector('#lmFabButton');if(!b)return;const u=ui(),p=8,w=b.offsetWidth||42,h=b.offsetHeight||42;b.style.left=Math.max(p,Math.min(innerWidth-w-p,u.x??innerWidth-w-p))+'px';b.style.top=Math.max(p,Math.min(innerHeight-h-p,u.y??120))+'px';b.style.right='auto';b.style.bottom='auto';}
function syncFab(){const b=document.querySelector('#lmFabButton');if(b)b.style.display=ui().showFab?'grid':'none';}
function ensureFab(){let b=document.querySelector('#lmFabButton');if(!b){b=document.createElement('button');b.id='lmFabButton';b.className='lm-fab';b.textContent='🩺';document.body.appendChild(b);}if(b.dataset.bound)return;b.dataset.bound='1';let d=null;b.onpointerdown=e=>{const r=b.getBoundingClientRect();d={id:e.pointerId,sx:e.clientX,sy:e.clientY,ox:e.clientX-r.left,oy:e.clientY-r.top,m:false};b.setPointerCapture?.(e.pointerId);};b.onpointermove=e=>{if(!d||d.id!==e.pointerId)return;const dx=e.clientX-d.sx,dy=e.clientY-d.sy;if(Math.hypot(dx,dy)>6)d.m=true;if(!d.m)return;const p=8,w=b.offsetWidth,h=b.offsetHeight;b.style.left=Math.max(p,Math.min(innerWidth-w-p,e.clientX-d.ox))+'px';b.style.top=Math.max(p,Math.min(innerHeight-h-p,e.clientY-d.oy))+'px';e.preventDefault();};b.onpointerup=e=>{if(!d)return;const moved=d.m;d=null;if(moved){const r=b.getBoundingClientRect(),u=ui();u.x=Math.round(r.left);u.y=Math.round(r.top);saveUI(u);}else open();};placeFab();syncFab();}
function ensureSettings(){const host=document.querySelector('#extensions_settings2')||document.querySelector('#extensions_settings');if(!host||document.querySelector('#lmSettings'))return;const w=document.createElement('div');w.id='lmSettings';w.className='lovemed-settings inline-drawer';w.innerHTML='<div class="inline-drawer-toggle inline-drawer-header"><b>🩺 LoveMed — Medical Card of Love</b><div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div></div><div class="inline-drawer-content"><button id="lmOpenSettings" class="menu_button">🩺 Открыть медицинскую карту</button><label><input id="lmShowSettingsFab" type="checkbox"> Показывать плавающую кнопку</label><p>Библиотека пользовательских предпочтений сохраняется отдельно от карты текущего персонажа.</p></div>';host.appendChild(w);w.querySelector('#lmOpenSettings').onclick=open;const c=w.querySelector('#lmShowSettingsFab');c.checked=ui().showFab;c.onchange=e=>{const u=ui();u.showFab=e.target.checked;saveUI(u);syncFab();};}
function ensureWand(){const m=document.querySelector('#extensionsMenu');if(!m||document.querySelector('#lmWand'))return;const x=document.createElement('div');x.id='lmWand';x.className='list-group-item flex-container flexGap5 interactable';x.innerHTML='<i class="fa-solid fa-stethoscope"></i><span>LoveMed — Медицинская карта</span>';x.onclick=e=>{e.preventDefault();open();};m.appendChild(x);}
function on(t,f){try{eventSource?.on?.(t,f);}catch{}}
function init(){ensureFab();ensurePanel();ensureSettings();ensureWand();refreshPrompt();on(event_types.CHAT_CHANGED,()=>setTimeout(()=>{ensureFab();ensureSettings();ensureWand();render();refreshPrompt();},250));on(event_types.MESSAGE_RECEIVED,()=>setTimeout(parseLatest,250));on(event_types.GENERATION_STARTED,()=>refreshPrompt({includeReaction:true}));on(event_types.GENERATION_ENDED,()=>{parseLatest();refreshPrompt();});on(event_types.CHARACTER_EDITED,refreshPrompt);window.addEventListener('resize',placeFab);setInterval(()=>{ensureFab();ensureSettings();ensureWand();},2000);}
init();
